API Harmonization
spruceid/siwe-ex pull request #22
Opened 2022-04-07 17:09 UTC by theosirian

This PR as discussed internally tries to harmonize all siwe libraries to a similar behavior across all different languages.

- [x] API uniformization across libraries
- [x] Improve message syntax checking
- [x] Improve error messages
- [x] Improve tests and adding siwe-ts test vectors

2022-04-08 12:10 UTC, awoie requested changes
lgtm except version bump and global test cases not being used but the latter can be done in a separate PR.

2022-04-08 12:10 UTC, awoie commented on native/siwe_ex/src/lib.rs
> +        verify,
can we bump version number of siwe-ex?

2022-04-08 12:10 UTC, awoie commented on test/siwe_test.exs
> +  test "helper functions are equivalent" do
should we use the global test vectors at some point?

2022-04-11 16:48 UTC, krhoda commented
References to `verify_time` should be removed and the tests changed from their existing format to one that uses the test vectors in the main repo. Otherwise, looks good to me.

2022-04-19 22:02 UTC, krhoda commented
Definitely still needs `siwe-rs` PR to come through first so we can point the `Cargo.toml` away from the local filesystem.

I've updated the tests to match the API changes, but I found issues passing optional parameters to `verify`, I'll try to change things so we use a struct which I think will solve our problems.

2022-04-19 22:31 UTC, krhoda commented
The tests are now updated, the strange thing is that the `siwe-rs`'s `verify` function seems to be accepting a bad signature as long as everything else is valid, as seen by the commented out `assert` in the tests, I want to understand why that is happening before calling it all good.

2022-04-19 23:03 UTC, krhoda commented
`verify` doesn't seem to reject bad messages from my testing, and it seems like it might be an underlying issue with `siwe-rs`, I have the latest `api-harmonization` branch but it still isn't working as expected.

2022-04-20 01:17 UTC, krhoda commented
Got the tests working with the new API, seems great to me. Just need to publish the changes to the rust crate, then we can change this repo's Cargo.toml to no longer point at the local fs.

2022-04-20 01:21 UTC, krhoda requested changes
Just get the `Cargo.toml` pointed a crate and not the local fs for `siwe` dep.

2022-05-23 15:17 UTC, krhoda commented
Looks great to me, tests work locally and no longer uses fs for `siwe` dep!

2022-05-23 15:17 UTC, krhoda approved these changes

2022-05-23 15:30 UTC, merged